# Generated by Django 4.2.7 on 2023-12-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trenz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='random@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='random2@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
