# Generated by Django 4.2.7 on 2023-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trenz', '0002_userprofile_email_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='user_messages', to='trenz.message'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pinned_stocks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
