# Generated by Django 4.2.7 on 2023-12-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trenz', '0003_userprofile_messages_userprofile_pinned_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='user2',
        ),
    ]
